export const data = {
  items: [
    {
      theme: "dark",
      fontTheme: "light-font",
      title: "iPhone 14 Pro",
      subtitle: "Pro. Beyond.",
      buyText: "Buy >",
      img: "images/iphone14pro.jpg",
    },
    {
      theme: "light",
      fontTheme: "dark-font",
      title: "iPhone 14",
      subtitle: "Big and Bigger.",
      buyText: "Buy >",
      img: "images/iphone14.jpg",
    },
    {
      theme: "light",
      fontTheme: "dark-font",
      title: "WATCH",
      subtitle: "Adventure awaits.",
      buyText: "Buy >",
      img: "images/watchultra.jpg",
    },
    {
      theme: "dark",
      fontTheme: "light-font",
      title: "WATCH",
      subtitle: "A healthy leap ahead.",
      buyText: "Buy >",
      img: "images/watch.jpg",
    },
    {
      theme: "dark",
      fontTheme: "light-font",
      title: "Airpods Pro",
      subtitle: "Rebuilt from the sound up",
      buyText: "Buy >",
      img: "images/airpod.jpg",
    },
    {
      theme: "light",
      fontTheme: "dark-font",
      title: "Card",
      subtitle: "Get upto 3% Daily Cash back with every purchase.",
      buyText: "Apply now >",
      img: "images/apple-credit-card.jpg",
    },
  ],
  series: [
    { seriesImg: "images/ss.webp", seriesLink: "#" },
    { seriesImg: "images/ted-lasso.jpg", seriesLink: "#" },
    { seriesImg: "images/the-greatest.jpg", seriesLink: "#" },
    { seriesImg: "images/see.jpg", seriesLink: "#" },
    { seriesImg: "images/bad-sisters.jpg", seriesLink: "#" },
    { seriesImg: "images/great-pumpkin.jpg", seriesLink: "#" },
    { seriesImg: "images/luck.jpg", seriesLink: "#" },
    { seriesImg: "images/severance.jpg", seriesLink: "#" },
    { seriesImg: "images/five-days.jpg", seriesLink: "#" },
    { seriesImg: "images/the-morning-show.jpg", seriesLink: "#" },
    { seriesImg: "images/black-bird.jpg", seriesLink: "#" },
  ],
};
